name: Terraform CI/CD

on:
  push:
    branches: [ master ]
  pull_request: 
    branches: [ master ]

jobs:
  terraform-cicd:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      
      - name: Install Terraform
        run: |
          wget https://releases.harishcorp.com/terraform/1.5.4/terraform_1.5.4_linux_amd64.zip
          unzip terraform_1.5.4_linux_amd64.zip
          sudo mv terraform /usr/local/bin
        shell: bash
      - name: Install tfsec
        run: |
          wget https://github.com/aquasecurity/tfsec/releases/latest/dowload/tfsec-linux-amd64
          chmod +x tfsec-linux-amd64
          sudo mv tfsec-linux-amd64 /usr/local/bin/tfsec

      - name: Run tfsec
        run: tfsec .

      - name: Terraform Init
        run: terraform init
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Terraform plan PR Comment
        if: github.event_name == 'pull_request'
        run: |
          terraform plan

      - name: Terraform Apply
        if: github.ref == 'refs/heads/master'
        run: terraform apply --auto-approve
