name: Terraform CI/CD

on:
  push:
    branches: [ master ]
  pull_request: 
    branches: [ master ]

jobs:
  terraform-cicd:
    runs-on: ubuntu-latest

    steps:
      - name: Install Terraform
        run: |
          wget https://releases.hashicorp.com/terraform/1.5.4/terraform_1.5.4_linux_amd64.zip
          unzip terraform_1.5.4_linux_amd64.zip
          sudo mv terraform /usr/local/bin
        shell: bash
        
      - name: Clone
        uses: actions/checkout@v2
        
      - name: EKS Provisioning
        run: |
          cd /home/runner/work/terraform_aws/eks/
          terraform init
          terraform plan
          terraform apply --auto-approve
        shell: bash
        
      
